services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "5433:5432"
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl -f http://0.0.0.0:8000/ || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
  bot:
    build: .
    command: python bot/bot.py
    volumes:
      - ./:/app
    env_file:
      - ./.env