# Generated by Django 3.2.6 on 2021-09-01 12:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessagerate',
            name='channel_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramchannel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, size=None, verbose_name='Тэги канала'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, size=None, verbose_name='Пользовательские фильтры'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usermessagerate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
