# Generated by Django 3.2.9 on 2021-12-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_array_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=130, verbose_name='ID сообщения')),
                ('channel_id', models.CharField(max_length=130, verbose_name='ID канала')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramuser')),
            ],
            options={
                'verbose_name': 'Собщение истории',
                'verbose_name_plural': 'Собщения истории',
            },
        ),
    ]
